apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: openstack-helm
  namespace: default
spec:
  interval: 5m0s
  url: https://gitlab.ics.muni.cz/cloud/g2/openstack-helm.git
  ref:
    branch: downstream
