apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/02-rook-ceph
patchesStrategicMerge:
  - 02-rook-ceph/01-rook-ceph-operator.yaml
  - 02-rook-ceph/02-rook-ceph-cluster.yaml
